---
- name: create file
  hosts: server2.example.com
  tasks:
  - name: Creating an empty file
    file:
      path: "/tmp/{{ deploy }}.txt"
      state: touch
      mode: '0644'
  - name: Display file created
    shell: ls -lrt
  - name: Hostname
    shell: hostname
