---
- name: create file
  hosts: server1.example.com
  become: yes
    
  tasks:
  - name: Check if file exists
    stat:
       path: /tmp/welcome.txt
    register: file_status
  - name: Fail if file exist
    fail:
       msg: "Fil already exists"
     when: file_status.stat.exists      
  - name: Creating an empty file
    file:
      path: "/tmp/welcome.txt"
      state: touch
      mode: '0644'
   
  
