---
- name: create file
  hosts: server2.example.com
  become: yes
  become_method: sudo
  
  tasks:
  - name: Creating an empty file
    file:
      path: "/tmp/roman.txt"
      state: touch
      mode: '0644'
